/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <iostream>
#include "chat.h"
#include "database.h"

DatabaseService db_service;

result *
send_2_svc(send_params *argp, struct svc_req *rqstp) {
  	std::cout << "send_2_svc :: Receiver: " << argp->to << "; Message: " << argp->message << "; Cookie: " << argp->cookie << std::endl;
	
	static result result;
  	
  	try {
		std::string login = db_service.get_user_login(argp->cookie);
    	db_service.add_message(std::string(argp->to), login, std::string(argp->message));

    	result.code = result_code::OK;
		result.descr = "Successful";
  	} catch(std::string error) {
	    result.code = result_code::FAIL;
	    result.descr = new char[error.length() + 1];
	    strcpy(result.descr, error.c_str());
  	}
	
	return &result;
}

login_result *
login_2_svc(login_params *argp, struct svc_req *rqstp) {
	std::cout << "login_2_svc :: Login: " << argp->login << "; Password: " << argp->password << std::endl;

	static login_result result;

	try {
		int cookie = db_service.login_user(argp->login, argp->password);

		result.cookie = cookie;
		result.res.code = result_code::OK;
		result.res.descr = "Successful";
	} catch(std::string error) {
		result.cookie = 0;
		result.res.code = result_code::FAIL;
		result.res.descr = new char[error.length() + 1];
	    strcpy(result.res.descr, error.c_str());
	}
	
	return &result;
}

result *
logout_2_svc(logout_params *argp, struct svc_req *rqstp) {
	std::cout << "login_2_svc :: Cookie: " << argp->cookie << std::endl;

	static result result;

	try {
		db_service.logout_user(argp->cookie);

		result.code = result_code::OK;
		result.descr = "Successful";
	} catch(std::string error) {
		result.code = result_code::FAIL;
		result.descr = new char[error.length() + 1];
	    strcpy(result.descr, error.c_str());
	}

	return &result;
}

receive_result *
receive_2_svc(receive_params *argp, struct svc_req *rqstp) {
	std::cout << "receive_2_svc :: Cookie: " << argp->cookie << std::endl;
	
	static receive_result result;
  	
  	try {
	    std::string login = db_service.get_user_login(argp->cookie);
	    std::vector<std::pair<std::string, std::string>> messages = db_service.get_messages(login);
	    std::cout << messages.size() <<std::endl;
	    result.data.data_len = messages.size();
	    result.data.data_val = new receive_message[messages.size()];
	    for (int i = 0; i < messages.size(); ++i) {
	    	receive_message buf;
	    	buf.from = new char[messages[i].first.length() + 1];
	    	buf.message = new char[messages[i].second.length() + 1];
	    	strcpy(buf.from, messages[i].first.c_str());
	    	strcpy(buf.message, messages[i].second.c_str());
	    	result.data.data_val[i] = buf;
	    }

	    result.res.code = result_code::OK;
  		result.res.descr = "Successful";
  	} catch(std::string error) {
	    result.data.data_len = 0;
	  	result.data.data_val = nullptr;
	    result.res.code = result_code::FAIL;
	    result.res.descr = new char[error.length() + 1];
	    strcpy(result.res.descr, error.c_str());
  	}

	return &result;
}

users_result *
users_2_svc(users_param *argp, struct svc_req *rqstp) {
	std::cout << "users_2_svc :: Cookie: " << argp->cookie << std::endl;

	static users_result result;

	try {
		std::vector<std::pair<std::string, bool>> users = db_service.users_list();

		result.data.data_len = users.size();
		result.data.data_val = new users_message[result.data.data_len];
		for (int i = 0; i < result.data.data_len; ++i) {
			result.data.data_val[i].login = (char*) users[i].first.c_str();
			result.data.data_val[i].online = users[i].second ? online_status::ONLINE : online_status::OFFLINE;
		}

		result.res.code = result_code::OK;
		result.res.descr = "Successful";
	} catch (std::string error) {
		result.res.code = result_code::FAIL;
		result.res.descr = new char[error.length() + 1];
	    strcpy(result.res.descr, error.c_str());
	}

	return &result;
}

result *
register_2_svc(register_params *argp, struct svc_req *rqstp) {
	std::cout << "register_2_svc :: Login: " << argp->login << "; Password: " << argp->password << std::endl;

	static result result;

	try {
		db_service.register_user(argp->login, argp->password);

		result.code = result_code::OK;
		result.descr = "Successful";
	} catch(std::string error) {
		result.code = result_code::FAIL;
		result.descr = new char[error.length() + 1];
	    strcpy(result.descr, error.c_str());
	}

	return &result;
}

// g++ -std=c++11  chat_server.c chat_svc.c chat_xdr.c -o chat_server -lnsl -lsqlite3 -w
